version: '3.8'

services:
  data-keeper:
    image: grishaem1/datakeeper:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - auth
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - HTTPS=${HTTPS}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - AUTH_HOST=${AUTH_HOST}
      - AUTH_PORT=${AUTH_PORT}
      - AUTH_TIMEOUT=${AUTH_TIMEOUT}
      - AUTH_JWT_KEY=${AUTH_JWT_KEY}
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: datakeeper
      POSTGRES_PASSWORD: datakeeper
      POSTGRES_DB: datakeeper
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  auth:
    image: grishaem1/userapp:latest
    ports:
      - "50051:50051"  # gRPC port
volumes:
  postgres_data: