url: localhost:8081
https: false
postgres_db:
  url: postgres://datakeeper:datakeeper@localhost:5432/datakeeper?sslmode=disable
auth_service:
  url: http://localhost:8080
  timeout: 5
  jwt_key: secret